{% set name = 'pcgr_test' %}
{% set version = os.environ.get('VERSION', '').replace('v.', '').replace('v', '') or '0.0.1' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../../

build:
  number: 0
  rpaths:
    - lib/
    - lib/R/library/

requirements:
  build:
    - curl
    - unzip
    - tar
    - pip
    - python>=3.7
    - r-base>=4.1.0
    - r-devtools
    - r-usethis
    - r-purrr
    - r-dplyr
    - r-stringr
    - r-tidyr
    - r-httr
    - r-git2r
    - r-data.table
    - r-magrittr
    - r-htmltools
    - r-caret
    - r-randomforest
    - r-plotly
    - r-ggplot2
    - r-dt
    - r-stringi
    - r-htmlwidgets
    - r-crosstalk
    - r-knitr
    - r-rmarkdown
    - r-biocmanager
    - bioconductor-variantannotation
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-bsgenome.hsapiens.ucsc.hg38
    - bioconductor-mutationalpatterns
    - r-flexdashboard
    - r-tidyverse
    - r-ggpubr
    - r-upsetr
    - r-log4r
  run:
    # PCGR: python
    - python>=3.7
    - r-base>=4.1.0
    - ensembl-vep
    - pip
    ##- numpy >=1.19.2
    - cython
    - scipy
    - pandas
    - cyvcf2
    - samtools
    - bedtools
    - vcfanno
    #
    # PCGR: other tools
    - tabix
    - vt
    ##- htslib
    - vcf2maf
    - nlopt
    - perl-bio-bigfile  # for Loftee (doesn't come with ensemble-vep, but will come with https://github.com/bioconda/bioconda-recipes/pull/18808 once merged)
    - r-devtools
    - r-usethis
    - r-purrr
    - r-dplyr
    - r-stringr
    - r-tidyr
    - r-httr
    - r-git2r
    - r-data.table
    - r-magrittr
    - r-htmltools
    - r-caret
    - r-randomforest
    - r-plotly
    - r-ggplot2
    - r-dt
    - r-stringi
    - r-htmlwidgets
    - r-crosstalk
    - r-knitr
    - r-log4r
    - r-rmarkdown
    - r-biocmanager
    - bioconductor-variantannotation
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
    - bioconductor-bsgenome.hsapiens.ucsc.hg38
    - bioconductor-mutationalpatterns
    - r-shiny
    - r-flexdashboard
    - r-tidyverse
    - r-ggpubr
    - r-upsetr

test:
  commands:
    - pcgr.py --version
    - '$R -e ".libPaths(R.home(\"library\")); library(pcgrr)"'
  imports:
    - annoutils

about:
  home: https://github.com/sigven/pcgr
  license: MIT
  summary: Personal Cancer Genome Reporter (PCGR) - variant interpretation report for precision cancer medicine
